# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c63f83d4d409b036d9f935ba9d4df3382de558259539a86b77b7ea2506bb82c4077d9f9c62cb20d08b156051a06e8f232e814e04de053f84484c8ad95fb52e02

test:
  secret_key_base: 12bd9f75417eba02aa581aaa0c7a0d05a2b35aca78669fee13d2b1824a3aaa26d01c33986b09f0075d4a8e16acee369f958f84da82c6c15588a8a0b21cb7427f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
